---
prometheus:
  prometheusSpec:
    retention: 6h
    resources:
      requests:
        cpu: 80m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 2Gi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 15m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 200Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 15m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

grafana:
  resources:
    requests:
      cpu: 50m
      memory: 300Mi
    limits:
      cpu: 100m
      memory: 512Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 15m
      memory: 24Mi
    limits:
      cpu: 50m
      memory: 64Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi