# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
---
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi
    retention: 5d
    retentionSize: 2Gi
    resources:
      requests:
        cpu: 80m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 2Gi
    # https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/monitoring.md#configure-prometheus
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 200Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 15m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

grafana:
  resources:
    requests:
      cpu: 50m
      memory: 400Mi
    limits:
      cpu: 100m
      memory: 700Mi
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      jsonData:
        timeout: 60
        maxlines: 1000

  # make Grafana persistent (Using Statefulset). Creates a Persistent Disk.
  persistence:
    enabled: true
    type: sts # Statefulset. `Deployment`can be used for test clusters
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheus-node-exporter:
  resources:
    requests:
      cpu: 8m
      memory: 24Mi
    limits:
      cpu: 50m
      memory: 64Mi

prometheusOperator:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi