{
 "title": "Pdfium - resources",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod)(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"^pdfium-.*\", container!~\"^(POD)?$\"}[$__rate_interval]) * 1000)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% memory limit across pods",
   "type": "timeseries",
   "description": "Total memory usage % across pods compared to memory limit. Values higher than 75% trigger autoscaling.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(\n    sum (\n        container_memory_usage_bytes{\n        namespace=\"default\",\n        container!~\"^(POD)?$\",\n        pod=~\"^pdfium.*\"\n        }\n    )\n    /\n    sum (\n        kube_pod_container_resource_limits{\n        namespace=\"default\",\n        resource=\"memory\",\n        pod=~\"^pdfium.*\"\n        }\n    )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"^pdfium-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus disk usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"prometheus-prometheus-stack-kube-prom-prometheus-db-prometheus-prometheus-stack-kube-prom-prometheus-0\"}/\nkubelet_volume_stats_available_bytes{persistentvolumeclaim=\"prometheus-prometheus-stack-kube-prom-prometheus-db-prometheus-prometheus-stack-kube-prom-prometheus-0\"}*100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Grafana disk usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"storage-prometheus-stack-grafana-0\"}/\nkubelet_volume_stats_available_bytes{persistentvolumeclaim=\"storage-prometheus-stack-grafana-0\"}*100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Ingress CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"ingress-nginx\", pod=~\"ingress-nginx-controller-.*\", container!~\"^(POD)?$\"}[$__rate_interval]) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}