{
 "title": "Pdfium - requests",
 "time": { "from": "2025-05-26T23:44:19.400Z", "to": "2025-05-27T00:44:19.400Z" },
 "panels": [
  {
   "title": "RPM (from ingress)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{path=\"/render\"}[$__rate_interval])*60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM (from service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gin_uri_request_total{uri=\"/render\"}[$__rate_interval])*60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests rate per path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (path) (\n  rate(nginx_ingress_controller_requests[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status codes for render",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status)(rate(nginx_ingress_controller_requests{path=\"/render\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(gin_request_duration_sum{uri=\"/render\"}[$__rate_interval])/rate(gin_request_duration_count{uri=\"/render\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Histogram quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(gin_request_duration_bucket{uri=\"/render\"}[$__rate_interval]) ))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(gin_request_duration_bucket{uri=\"/render\"}[$__rate_interval]) ))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(gin_request_duration_bucket{uri=\"/render\"}[$__rate_interval]) ))",
     "legendFormat": "50th percentile"
    }
   ]
  }
 ]
}